// Account[] accts = new List<Account>{
//     new Account(Name='Account1')};
// Database.UpsertResult[] srList = Database.upsert(accts, false);

// // Iterate through each returned result
// for (Database.UpsertResult sr : srList) {
//     if (sr.isSuccess()) {
//         // Operation was successful, so get the ID of the record that was processed
//         System.debug('Successfully inserted account. Account ID: ' + sr.getId());
//     }
//     else {
//         // Operation failed, so get all errors                
//         for(Database.Error err : sr.getErrors()) {
//             System.debug('The following error has occurred.');                    
//             System.debug(err.getStatusCode() + ': ' + err.getMessage());
//             System.debug('Account fields that affected this error: ' + err.getFields());
//         }
//     }
// }

Set<String> s1 = new Set<String>();
// Add two strings to it
s1.add('item1');
s1.add('item2');
System.debug(s1);
